#! /bin/sh

#launch picom
killall "picom"
picom --experimental-backends &

sxhkd &

#launch polybar 
$HOME/.config/polybar/launch.sh

#set wallpaper
nitrogen --set-scaled /home/linux/Pictures/Wallpapers/wallpfossa.jpeg


bspc monitor -d I II III IV V VI VII VIII IX X


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#configs 

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         32
bspc config window_gap          10 
 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Disables the cross pointer
xsetroot -cursor_name left_ptr &
